baseurl = "/"
languageCode = "en-us"
title = "Zhenguo Zhang's Blog"
theme = "hugo-theme-diary"
googleAnalytics = "UA-123166861-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# added settings
hasCJKLanguage = false # no chinese/japanese/korean in content
#logFile = "site.log"
publishDir = "public"
staticDir = "static"
enableEmoji = true # allow Emoji emotions

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
	  weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
	  weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/fortune9/blogdown-everyday"
	  weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/fortunezhang"
	  weight = 5

[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/zhenguo-zhang-418b0220/"
	  weight = 4

[[menu.main]]
    url = "/categories"
    name = "Categories"
    weight = 6

[[menu.main]]
    url = "/tags"
    name = "Tags"
    weight = 7

[[menu.main]]
    url = "/posts"
    name = "Archive"
    weight = 8

[params]
	subtitle = "Sharing makes life better"
    description = "Tips in bioinformatics, computer use, statistics, and data analysis"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "python", "markdown", "bash"]
    highlightjsTheme = "github"
    
    enableMathJax=true
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs/mathjax"
    MathJaxVersion = "3.0.0"
    # google search
	# <script async src="https://cse.google.com/cse.js?cx=a57129bb44552a6f6"></script>
	# <div class="gcse-search"></div>

	googleSearchCode = "a57129bb44552a6f6"
    
    leftsidebar = false
	comment = true
	disqusShortname = "fortune9-netlify"
    
[params.logo]
    url = "logo1.png"
    width = 50
    height = 50
    alt = "Logo"

[taxonomies]
   tag = "tags"
   category = "categories"

# code hightlight
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

# add plugins
[[plugins]]
	package = "@netlify/plugin-sitemap"
	# see configuration here https://github.com/netlify-labs/netlify-plugin-sitemap
	[plugins.inputs]
		exclude=[
			"./google3759aac0a838253c.html",
			"./robots.txt"
		]
		prettyURLs = false
