baseurl = "/"
languageCode = "en-us"
title = "Zhenguo Zhang's Blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "fortune9"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
	weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
	weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/fortune9/blogdown-everyday"
	weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/fortunezhang"
	weight = 5

[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/zhenguo-zhang-418b0220/"
	weight = 4

[params]
    description = "A website to share wisdom"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

