baseurl = "/"
languageCode = "en-us"
title = "Zhenguo Zhang's Blog"
theme = "hugo-theme-diary"
googleAnalytics = "UA-123166861-1"
disqusShortname = "fortune9"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# added settings
hasCJKLanguage = false # no chinese/japanese/korean in content
#logFile = "site.log"
publishDir = "public"
staticDir = "static"
enableEmoji = true # allow Emoji emotions

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
	  weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
	  weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/fortune9/blogdown-everyday"
	  weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/fortunezhang"
	  weight = 5

[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/zhenguo-zhang-418b0220/"
	  weight = 4

[[menu.main]]
    url = "/categories"
    name = "Categories"
    weight = 6

[[menu.main]]
    url = "/tags"
    name = "Tags"
    weight = 7

[[menu.main]]
    url = "/posts"
    name = "Archive"
    weight = 8

[params]
    description = "A website to lighten lives"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
    enableMathJax=true
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    # google search
    googleSearchCode = "https://cse.google.com/cse.js?cx=a688ecc156c78aa42"
    
    leftsidebar = false
    
    [params.logo]
    url = "logo1.png"
    width = 50
    height = 50
    alt = "Logo"

[taxonomies]
   tag = "tags"
   category = "categories"

# code hightlight
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4